{{- if .Values.minio.enabled -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "storagetron.minioName" . }}
  labels:
    {{- include "storagetron.labels" . | nindent 4 }}
    app.kubernetes.io/component: minio
spec:
  serviceName: {{ include "storagetron.minioName" . }}
  replicas: 1
  selector:
    matchLabels:
      {{- include "storagetron.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: minio
  template:
    metadata:
      labels:
        {{- include "storagetron.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: minio
    spec:
      containers:
        - name: minio
          image: "{{ .Values.minio.image.repository }}:{{ .Values.minio.image.tag }}"
          imagePullPolicy: {{ .Values.minio.image.pullPolicy }}
          args:
            - server
            - /data
            - --console-address
            - ":9001"
          ports:
            - name: api
              containerPort: 9000
              protocol: TCP
            - name: console
              containerPort: 9001
              protocol: TCP
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "storagetron.fullname" . }}
                  key: MINIO_ROOT_USER
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "storagetron.fullname" . }}
                  key: MINIO_ROOT_PASSWORD
          volumeMounts:
            - name: data
              mountPath: /data
          {{- with .Values.minio.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
  {{- if .Values.minio.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        {{- if .Values.minio.persistence.storageClass }}
        storageClassName: {{ .Values.minio.persistence.storageClass | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.minio.persistence.size }}
  {{- else }}
      volumes:
        - name: data
          emptyDir: {}
  {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "storagetron.minioName" . }}
  labels:
    {{- include "storagetron.labels" . | nindent 4 }}
    app.kubernetes.io/component: minio
spec:
  type: {{ .Values.minio.service.type }}
  ports:
    - port: {{ .Values.minio.service.apiPort }}
      targetPort: api
      protocol: TCP
      name: api
    - port: {{ .Values.minio.service.consolePort }}
      targetPort: console
      protocol: TCP
      name: console
  selector:
    {{- include "storagetron.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: minio
{{- end }}
