apiVersion: v1
kind: Secret
metadata:
  name: {{ include "storagetron.fullname" . }}
  labels:
    {{- include "storagetron.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ include "storagetron.databaseUrl" . | quote }}
  S3_ACCESS_KEY: {{ include "storagetron.s3AccessKey" . | quote }}
  S3_SECRET_KEY: {{ include "storagetron.s3SecretKey" . | quote }}
  BACKUP_SECRET_KEY: {{ .Values.api.backup.key | quote }}
  {{- if .Values.postgresql.enabled }}
  POSTGRES_USER: {{ .Values.postgresql.auth.username | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.auth.password | quote }}
  POSTGRES_DB: {{ .Values.postgresql.auth.database | quote }}
  {{- end }}
  {{- if .Values.minio.enabled }}
  MINIO_ROOT_USER: {{ .Values.minio.auth.rootUser | quote }}
  MINIO_ROOT_PASSWORD: {{ .Values.minio.auth.rootPassword | quote }}
  {{- end }}
