{{- if not .Values.secret.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "storagetron.fullname" . }}
  labels:
    {{- include "storagetron.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.secret.keys.databaseUrl | quote }}: {{ include "storagetron.databaseUrl" . | quote }}
  {{ .Values.secret.keys.s3AccessKey | quote }}: {{ include "storagetron.s3AccessKey" . | quote }}
  {{ .Values.secret.keys.s3SecretKey | quote }}: {{ include "storagetron.s3SecretKey" . | quote }}
  {{ .Values.secret.keys.backupSecretKey | quote }}: {{ .Values.api.backup.key | quote }}
  {{- if .Values.postgresql.enabled }}
  {{ .Values.secret.keys.postgresqlUsername | quote }}: {{ .Values.postgresql.auth.username | quote }}
  {{ .Values.secret.keys.postgresqlPassword | quote }}: {{ .Values.postgresql.auth.password | quote }}
  {{ .Values.secret.keys.postgresqlDatabase | quote }}: {{ .Values.postgresql.auth.database | quote }}
  {{- end }}
  {{- if .Values.minio.enabled }}
  {{ .Values.secret.keys.minioRootUser | quote }}: {{ .Values.minio.auth.rootUser | quote }}
  {{ .Values.secret.keys.minioRootPassword | quote }}: {{ .Values.minio.auth.rootPassword | quote }}
  {{- end }}
{{- end }}
