{{- if .Values.web.podDisruptionBudget.enabled -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "storagetron.webName" . }}
  labels:
    {{- include "storagetron.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  {{- if .Values.web.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.web.podDisruptionBudget.maxUnavailable }}
  {{- else }}
  minAvailable: {{ .Values.web.podDisruptionBudget.minAvailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "storagetron.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: web
{{- end }}
